-- entities
CREATE TABLE COMPILATION_UNIT ( ID INT, NAME VARCHAR(2048), PACKAGE VARCHAR(2048) );
CREATE TABLE CLASS ( ID INT, NAME VARCHAR(2048), IS_ABSTRACT INT, IS_FINAL INT, IS_PUBLIC INT, CU_ID INT );
CREATE TABLE INTERFACE ( ID INT, NAME VARCHAR(2048), IS_FINAL INT, IS_PUBLIC INT, CU_ID INT );
CREATE TABLE ANNOTATION ( ID INT, NAME VARCHAR(2048), IS_PUBLIC INT, CU_ID INT );
CREATE TABLE ENUMERATION ( ID INT, NAME VARCHAR(2048), IS_PUBLIC INT, CU_ID INT );
CREATE TABLE FIELD ( ID INT, NAME VARCHAR(4096), TYPE VARCHAR(512), IS_PUBLIC INT, IS_STATIC INT, IS_FINAL INT, IS_TRANSIENT INT, TYPE_ID INT );
CREATE TABLE CONSTRUCTOR ( ID INT, NAME VARCHAR(4096), IS_PUBLIC INT, TYPE_ID INT );
CREATE TABLE METHOD ( ID INT, NAME VARCHAR(4096), IS_ABSTRACT INT, IS_FINAL INT, IS_PUBLIC INT, TYPE_ID INT );
CREATE TABLE PARAMETER ( ID INT, NAME VARCHAR(4096), TYPE VARCHAR(512), METHOD_ID INT );

-- relations
CREATE TABLE EXTENDS ( TYPE_ID INT, EXTENDED_TYPE_ID INT ); -- KEY = (TYPE_ID, EXTENDED_TYPE_ID)
CREATE TABLE IMPLEMENTS ( CLASS_ID INT, INTERFACE_ID INT ); -- KEY = (CLASS_ID, INTERFACE_ID)
